language: node_js
node_js:
- node
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - plastikfan@zoho.com
    on_success: never
    on_failure: always
after_script: npm run coveralls
