language: node_js
node_js:
- node
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - plastikfan@zoho.com
    on_success: never
    on_failure: always
after_script: npm run coveralls
env:
  global:
    secure: OXvBFC5G7AqtgNC+6UBxal7s7OG5dlgGlXCS3wWTbk/MWoP3/QswihZ8BxKnxYHCNCvGRgXkMFKRSWqSqb0/gLPhwnyJYv+UOSXmStcAqRInO5pJxNOt2X4XjQ8IIBO9K9O2tGQcb68Sc0J5mSN6GlwuwCMTMdlnuBSfe7vdvC6NoT1nI9l+oZQwvYsMONI2fR/ouf6UjWryRL8jscvqlMFoixuSTqSFzXfXNaP37O8IiaV5BpEDaWm3Xt8ugA7U7UWFGQVOnL51wL7HUbLojlgBi+wc3MIuRmn4Ne0MIYkNTxUXv02CN0+RnN0EHDzPRpxV50iD83rHqbBasEGDqzkfkj/LIWPTEilJiCBEpyq8yLUF5z8gMyZMLzzuv94rRBJEalkmoiMoBdDDgMM2ObzWF1Mx23ZrbAQzZVQZQqXbD6vVFLhY5oxKOi2tSqFgROlqgZrJb+rXzv66ye1w81JbyhOhOpfcAFyJ5Cv2oiZI2JsySHbalRhayFQEqVCxqVpPK5fhqBzOhty7TW3hoiebAGX7D2zLpvsFnIrwxX+L7zGqNb5bAKLQo7D2u4CPvhw24DQQLMeFooxyM7/ttjaF9i3R4r22fnNBpJBQjT0gloK1uahcBijCfgh3q7/5C1/t9x5FUZn+tOLobueOmdbRbF7L0nFE+fe0T1u2Pyk=
